const fs = require('fs');
const path = require('path');

const productsFile = path.join(__dirname, 'src/data/products.ts');

const mappings = [
    // Corporate
    { file: 'insulated-water-bottles.jpg', title: 'Insulated Water Bottles', subtitle: 'Double-Wall Vacuum Flasks', desc: 'Keep beverages at the perfect temperature all day with these sleek double-wall vacuum insulated bottles. Ideal for corporate events and employee appreciation gifts.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'red-corporate-gift-set.jpg', title: 'Red Executive Suite', subtitle: 'Premium Corporate Combo', desc: 'A striking red-themed executive gift set featuring a diary, pen, and accessories. Commands attention and makes a bold statement at any corporate event.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'metallic-executive-pens.jpg', title: 'Metallic Executive Pens', subtitle: 'Precision Writing Instruments', desc: 'Refined metallic-finish pens that bring gravitas to every signature. A timeless corporate essential for boardroom meetings and executive desks.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'blue-diary-pen-set.jpg', title: 'Blue Diary & Pen Set', subtitle: 'Classic Stationery Duo', desc: 'An elegant blue-toned diary paired with a matching premium pen. The perfect combination for professionals who value organization and style.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'black-desktop-essentials.jpg', title: 'Black Desktop Essentials', subtitle: 'Modern Desk Companion', desc: 'A sleek all-black desktop set featuring essential office accessories. Designed to bring order and sophistication to any modern workspace.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'blue-flask-diary-set.jpg', title: 'Blue Flask & Diary Set', subtitle: 'Executive Hydration Suite', desc: 'A premium blue flask paired with a matching executive diary. The ideal duo for the modern professional who stays hydrated and organized.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'teal-executive-diary.jpg', title: 'Teal Executive Diary', subtitle: 'Vibrant Professional Journal', desc: 'A beautifully bound teal diary with premium pages for daily planning. Its vibrant hue adds a splash of personality to corporate gifting.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'camo-sling-bag.jpg', title: 'Camo Sling Bag', subtitle: 'Urban Adventure Carry', desc: 'A rugged yet stylish camouflage sling bag perfect for on-the-go professionals. Compact enough for daily commute, spacious enough for essentials.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'deco-bottle-umbrellas.jpg', title: 'Deco Bottle Umbrellas', subtitle: 'Compact Designer Shields', desc: 'Innovative bottle-shaped umbrellas with decorative patterns. A clever and practical gift that combines clever design with everyday utility.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'katzy-blue-backpack.jpg', title: 'Katzy Blue Backpack', subtitle: 'Professional Travel Companion', desc: 'A vibrant blue backpack with multiple compartments and ergonomic design. Built for the modern professional who balances work and adventure.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'black-flask-pen-set.jpg', title: 'Black Flask & Pen Set', subtitle: 'Noir Executive Duo', desc: 'A sophisticated all-black flask and pen set that exudes professionalism. The perfect gift for executives who appreciate understated elegance.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'tan-leather-essentials.jpg', title: 'Tan Leather Essentials', subtitle: 'Heritage Leather Collection', desc: 'A luxurious tan leather set featuring timeless accessories. Crafted from premium leather, each piece develops a beautiful patina over time.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },
    { file: 'colorful-steel-mugs.jpg', title: 'Colorful Steel Mugs', subtitle: 'Vibrant Drinkware Collection', desc: 'A cheerful collection of powder-coated stainless steel mugs in an array of vivid colors. Durable, stylish, and perfect for team gifting.', cat: 'Corporate Studio', img: '/assets/images/corporate/', href: '/corporate' },

    // Branded
    { file: 'cow-lotus-coasters.jpg', title: 'Cow Lotus Coasters', subtitle: 'Pichwai Art Ensemble', desc: 'Exquisite coasters adorned with traditional Pichwai motifs of sacred cows and lotus blooms. Each piece is a miniature canvas of Indian folk art.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'milton-insulated-mugs.jpg', title: 'Milton Insulated Mugs', subtitle: 'Premium Thermal Drinkware', desc: 'Milton-branded insulated mugs that keep your beverages at the perfect temperature. Trusted quality meets elegant design for discerning recipients.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'colorful-jewelry-boxes.jpg', title: 'Colorful Jewelry Boxes', subtitle: 'Artisan Treasure Keepers', desc: 'Vibrant handcrafted jewelry boxes in an assortment of radiant colors. Each box is a delightful keepsake that brings joy to organizing precious trinkets.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'cow-lotus-wooden-boxes.jpg', title: 'Cow Lotus Wooden Boxes', subtitle: 'Pichwai Heritage Storage', desc: 'Beautifully hand-painted wooden boxes featuring Pichwai cow and lotus motifs. A fusion of traditional artistry and functional elegance for sacred keepsakes.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'capsule-umbrellas.jpg', title: 'Capsule Umbrellas', subtitle: 'Ultra-Compact Rain Shields', desc: 'Cleverly designed capsule-shaped umbrellas that fit in any bag or pocket. A perfect blend of innovation and practicality for stylish rain protection.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'wooden-incense-holders.jpg', title: 'Wooden Incense Holders', subtitle: 'Hand-Carved Aroma Stands', desc: 'Intricately carved wooden incense holders that bring serenity to any space. Each piece showcases the artisan\'s dedication to traditional woodcraft.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'bamboo-premium-gift-set.jpg', title: 'Bamboo Premium Gift Set', subtitle: 'Eco-Luxury Ensemble', desc: 'A sustainably sourced bamboo gift set that embodies eco-conscious luxury. Perfect for those who appreciate nature-inspired premium gifting.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'silver-leaf-idols.jpg', title: 'Silver Leaf Idols', subtitle: 'Divine Silver Figurines', desc: 'Graceful silver-leaf finished deity figurines that radiate spiritual elegance. These sacred idols make for auspicious and memorable gifts.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'wooden-incense-stand.jpg', title: 'Wooden Incense Stand', subtitle: 'Artisan Fragrance Base', desc: 'A beautifully crafted wooden incense stand that serves as both a functional holder and a decorative accent. Brings warmth and tradition to any room.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'lotus-haldi-kumkum.jpg', title: 'Lotus Haldi Kumkum', subtitle: 'Sacred Ritual Container', desc: 'An ornate lotus-shaped Haldi Kumkum container for traditional ceremonies. A beautiful blend of devotion and artisanal craftsmanship.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'pink-flower-umbrella.jpg', title: 'Pink Flower Umbrella', subtitle: 'Floral Fashion Shield', desc: 'A charming pink umbrella adorned with delicate floral patterns. This fashionable accessory brightens even the rainiest of days.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'digital-desktop-clock.jpg', title: 'Digital Desktop Clock', subtitle: 'Modern Time Display', desc: 'A sleek digital desktop clock with a contemporary design. Features clear display and multiple functions — a stylish addition to any desk.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'floral-tumblers.jpg', title: 'Floral Tumblers', subtitle: 'Botanical Drinkware', desc: 'Elegant tumblers featuring delicate floral artwork. These eye-catching vessels transform your daily hydration into a visual delight.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'gold-kamadhenu-statue.jpg', title: 'Gold Kamadhenu Statue', subtitle: 'Sacred Gold Figurine', desc: 'A magnificent gold-finished Kamadhenu statue symbolizing divine abundance and prosperity. A revered spiritual gift for auspicious occasions.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'gold-peacock-box.jpg', title: 'Gold Peacock Box', subtitle: 'Royal Treasure Chest', desc: 'An opulent gold-finished box adorned with intricate peacock motifs. This regal container is perfect for storing precious keepsakes and jewelry.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'silver-kamadhenu-statue.jpg', title: 'Silver Kamadhenu Statue', subtitle: 'Sacred Silver Figurine', desc: 'A beautifully detailed silver-finished Kamadhenu statue representing divine blessings. An auspicious gift that brings grace to any sacred space.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'silver-feather-incense-holder.jpg', title: 'Silver Feather Incense', subtitle: 'Elegant Aroma Holder', desc: 'A graceful silver-toned feather-shaped incense holder that combines artistic beauty with spiritual function. A unique accent for serene spaces.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'digital-handheld-fans.jpg', title: 'Digital Handheld Fans', subtitle: 'Portable Cooling Gadgets', desc: 'Compact and colorful handheld digital fans for instant refreshment. A fun, practical gift that keeps you cool wherever you go.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'pichwai-cow-tray.jpg', title: 'Pichwai Cow Tray', subtitle: 'Heritage Serving Art', desc: 'A stunning serving tray featuring traditional Pichwai cow artwork. This functional art piece brings Indian heritage to your dining experience.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },
    { file: 'color-changing-alarm-clock.jpg', title: 'Color Changing Alarm Clock', subtitle: 'LED Mood Timepiece', desc: 'A mesmerizing alarm clock that cycles through a spectrum of vibrant LED colors. A modern bedside companion that wakes you up in style.', cat: 'Branded Gift', img: '/assets/images/branded/', href: '/collections/branded' },

    // Promotional
    { file: 'floral-mugs-set.jpg', title: 'Floral Mugs Set', subtitle: 'Botanical Ceramic Collection', desc: 'A delightful set of ceramic mugs adorned with vibrant floral patterns. Perfect for brightening up morning routines and team tea breaks.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'quote-wall-hangings.jpg', title: 'Quote Wall Hangings', subtitle: 'Inspirational Decor Art', desc: 'Beautifully designed wall hangings featuring motivational quotes. These inspiring pieces add character and positive energy to any space.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'round-wall-plates.jpg', title: 'Round Wall Plates', subtitle: 'Decorative Display Discs', desc: 'Elegant round decorative wall plates that serve as stunning focal points. Each plate features intricate designs perfect for home or office decor.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'jute-drawstring-bags.jpg', title: 'Jute Drawstring Bags', subtitle: 'Eco-Friendly Carry Pouches', desc: 'Sustainable jute drawstring bags that marry eco-consciousness with everyday practicality. An ideal branded giveaway for environmentally minded events.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'wooden-key-holders.jpg', title: 'Wooden Key Holders', subtitle: 'Artisan Wall Organizers', desc: 'Handcrafted wooden key holders that add rustic charm to your entryway. A thoughtful promotional gift that recipients will use every single day.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'printed-jute-bags.jpg', title: 'Printed Jute Bags', subtitle: 'Custom Eco Totes', desc: 'Durable printed jute bags that carry your brand message sustainably. These eco-friendly totes make a lasting impression at events and trade shows.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'designer-wall-clocks.jpg', title: 'Designer Wall Clocks', subtitle: 'Statement Timepieces', desc: 'Eye-catching designer wall clocks that elevate any room\'s aesthetic. A promotional gift that reminds recipients of your brand every moment of the day.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'custom-photo-frames.jpg', title: 'Custom Photo Frames', subtitle: 'Personalized Memory Displays', desc: 'Elegant photo frames ready for custom branding and personalization. These cherished keepsakes hold precious memories and your brand close to heart.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'lunch-box-sets.jpg', title: 'Lunch Box Sets', subtitle: 'Gourmet Meal Carriers', desc: 'Practical multi-tier lunch box sets that make meals on the go a delight. A daily-use promotional gift that keeps your brand at the table.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'insulated-lunch-bags.jpg', title: 'Insulated Lunch Bags', subtitle: 'Thermal Meal Totes', desc: 'Stylish insulated lunch bags that keep meals fresh and organized. A practical gift that combines brand visibility with everyday convenience.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'stainless-steel-bottles.jpg', title: 'Stainless Steel Bottles', subtitle: 'Durable Hydration Vessels', desc: 'Premium stainless steel water bottles built to last. These sleek vessels combine durability with modern aesthetics for maximum brand impact.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'canvas-tote-bags.jpg', title: 'Canvas Tote Bags', subtitle: 'Versatile Carry-Alls', desc: 'Sturdy canvas tote bags perfect for everyday use and brand promotion. A versatile, eco-conscious gift that goes everywhere with your recipients.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'metallic-water-bottles.jpg', title: 'Metallic Water Bottles', subtitle: 'Shimmer Hydration Flasks', desc: 'Gleaming metallic-finish water bottles that stand out from the crowd. A premium hydration companion that makes your brand shine.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'ceramic-coffee-mugs.jpg', title: 'Ceramic Coffee Mugs', subtitle: 'Classic Morning Vessels', desc: 'Quality ceramic coffee mugs ideal for custom branding and daily enjoyment. The quintessential promotional gift for coffee lovers everywhere.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'bamboo-desk-organizers.jpg', title: 'Bamboo Desk Organizers', subtitle: 'Sustainable Workspace Tidiers', desc: 'Eco-friendly bamboo desk organizers that bring natural elegance to workspaces. A thoughtful gift that promotes sustainability and productivity.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'leather-notebooks.jpg', title: 'Leather Notebooks', subtitle: 'Executive Writing Journals', desc: 'Premium leather-bound notebooks for the discerning professional. These luxurious journals make every note feel important and every idea worth keeping.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'portable-chargers.jpg', title: 'Portable Chargers', subtitle: 'On-the-Go Power Banks', desc: 'Compact portable chargers that keep devices powered throughout the day. A modern tech gift that ensures your brand is always within reach.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'wireless-earbuds.jpg', title: 'Wireless Earbuds', subtitle: 'Premium Audio Companions', desc: 'Sleek wireless earbuds delivering crisp audio quality. A premium tech promotional gift that recipients will use and appreciate daily.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'bluetooth-speakers.jpg', title: 'Bluetooth Speakers', subtitle: 'Portable Sound Systems', desc: 'Compact Bluetooth speakers with rich, room-filling sound. An impressive promotional gift that amplifies your brand alongside great music.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },
    { file: 'smart-fitness-bands.jpg', title: 'Smart Fitness Bands', subtitle: 'Wellness Tech Trackers', desc: 'Feature-packed smart fitness bands for health-conscious professionals. A modern wellness gift that shows your brand cares about well-being.', cat: 'Promotional Gifts', img: '/assets/images/promotional/', href: '/collections/promotional' },

    // Return Gifts
    { file: 'assorted-enamel-dibbi-collection.jpg', title: 'Assorted Enamel Dibbi Collection', subtitle: 'Vibrant Meenakari Set', desc: 'A stunning collection of assorted enamel dibbis in various colors and patterns. Each piece showcases exquisite Meenakari craftsmanship, perfect as wedding return gifts.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'divine-statue-keepsakes.jpg', title: 'Divine Statue Keepsakes', subtitle: 'Sacred Deity Figurines', desc: 'Beautifully crafted divine statue keepsakes featuring revered deities. These auspicious figurines bring blessings and spiritual grace to your guests\' homes.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'ganesha-enamel-dibbi-gold.jpg', title: 'Ganesha Enamel Dibbi Gold', subtitle: 'Sacred Gold Meenakari Box', desc: 'An exquisite gold-toned enamel dibbi featuring Lord Ganesha. This auspicious container blends devotion with artisanal beauty for a truly blessed keepsake.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'lotus-enamel-diya-purple.jpg', title: 'Lotus Enamel Diya Purple', subtitle: 'Purple Meenakari Lamp', desc: 'A resplendent purple lotus-shaped enamel diya that radiates spiritual warmth. Hand-painted with delicate Meenakari patterns for ceremonial elegance.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'lotus-enamel-diya-yellow.jpg', title: 'Lotus Enamel Diya Yellow', subtitle: 'Golden Meenakari Lamp', desc: 'A radiant yellow lotus-shaped enamel diya bringing sunshine and blessings. Its warm hue and intricate enamel work make every pooja luminous.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'modern-insulated-tiffin-set.jpg', title: 'Modern Insulated Tiffin Set', subtitle: 'Contemporary Meal Carrier', desc: 'A sleek, modern insulated tiffin set that keeps meals warm and fresh. A practical yet elegant return gift that blends utility with contemporary style.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'peacock-blossom-tin-box.jpg', title: 'Peacock Blossom Tin Box', subtitle: 'Printed Keepsake Container', desc: 'A charming tin box adorned with peacock and blossom prints. This delightful container is perfect for storing small treasures and sweet memories.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'peacock-enamel-dibbi-classic.jpg', title: 'Peacock Enamel Dibbi Classic', subtitle: 'Traditional Meenakari Box', desc: 'A classic peacock-themed enamel dibbi with timeless Meenakari artistry. Its vibrant colors and heritage design make it an unforgettable keepsake.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'peacock-enamel-dibbi-gold.jpg', title: 'Peacock Enamel Dibbi Gold', subtitle: 'Gold Meenakari Treasure Box', desc: 'A luxurious gold-finished peacock enamel dibbi with ornate detailing. This regal keepsake captures the majesty of Indian craftsmanship.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'peacock-enamel-dibbi-royal.jpg', title: 'Peacock Enamel Dibbi Royal', subtitle: 'Royal Meenakari Container', desc: 'A royal peacock enamel dibbi in rich, regal tones. This majestic container embodies the grandeur of traditional Indian artistry.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'peacock-enamel-dibbi-single.jpg', title: 'Peacock Enamel Dibbi Single', subtitle: 'Solo Meenakari Keepsake', desc: 'An elegant single peacock enamel dibbi, perfect as an individual return gift. Its compact size and vivid artistry make it a cherished memento.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'peacock-enamel-dibbi-trio.jpg', title: 'Peacock Enamel Dibbi Trio', subtitle: 'Triple Meenakari Set', desc: 'A magnificent trio of peacock enamel dibbis in complementary designs. This set of three offers a lavish spread of color and traditional craftsmanship.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'pink-polka-enamel-box.jpg', title: 'Pink Polka Enamel Box', subtitle: 'Playful Meenakari Container', desc: 'A delightful pink polka-dotted enamel box with a cheerful, modern twist on traditional Meenakari. A fun and feminine keepsake for your guests.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'royal-peacock-gold-diya-set.jpg', title: 'Royal Peacock Gold Diya Set', subtitle: 'Majestic Gold Lamp Collection', desc: 'A grand set of gold-finished peacock diyas that illuminate celebrations with regal splendor. Each diya is a masterpiece of ornamental craftsmanship.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' },
    { file: 'soup-bowl-combo-blue.jpg', title: 'Soup Bowl Combo Blue', subtitle: 'Ceramic Bowl & Spoon Set', desc: 'A charming blue ceramic soup bowl paired with a matching spoon. This practical and stylish combo makes for a heartwarming return gift.', cat: 'Wedding Return Gifts', img: '/assets/images/return_gift/', href: '/collections/wedding' }
];

const productsContent = fs.readFileSync(productsFile, 'utf8');

// Find "];" and insert before it
const lastIndex = productsContent.lastIndexOf('];');
if (lastIndex === -1) {
    console.log("ERROR: Could not find end of array.");
    process.exit(1);
}

const before = productsContent.substring(0, lastIndex);
// Check if 'before' already ends with a comma (after trimming whitespace)
const trimmed = before.trimEnd();
const needsComma = !trimmed.endsWith(',');

let entries = [];
let idCounter = 100;

for (const m of mappings) {
    const idStr = "new-" + m.cat.replace(/[^a-zA-Z]/g, '').toLowerCase() + "-" + (idCounter++);
    const escapedDesc = m.desc.replace(/'/g, "\\'");

    entries.push(`    {
        id: "${idStr}",
        title: "${m.title}",
        subtitle: "${m.subtitle}",
        description: "${m.desc}",
        img: "${m.img}${m.file}",
        category: "${m.cat}",
        href: "${m.href}"
    }`);
}

const separator = needsComma ? ',\n' : '\n';
const newContent = before.trimEnd() + separator + entries.join(",\n") + "\n];\n";
fs.writeFileSync(productsFile, newContent, 'utf8');
console.log("Done! Added " + entries.length + " products with unique descriptions.");
